'use strict';
const data=window.STUDIO_DATA, KEY='lomb.studio.v1';
let decisions={}, tab='review';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
function valid(d){const p=data.items.find(p=>p.key===d.key);return p&&p.source_sha256&&d.source_sha256===p.source_sha256&&['approve','edit','reject'].includes(d.action)&&typeof d.note==='string'&&d.note.length<=10000&&(!d.collection||data.collections.includes(d.collection))&&(d.action==='approve'||!d.collection)&&(d.action!=='edit'||d.note.trim());}
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');for(const d of Object.values(saved))if(valid(d))decisions[d.key]=d;}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(decisions));$('#save').textContent='Draft saved on this device only. Copy and send in this task.';}catch{$('#save').textContent='Device storage unavailable. Export before closing this page.';}}
function link(label,url){const a=el('a',label);a.href=url;a.target='_blank';a.rel='noopener';return a;}
function status(p){const d=decisions[p.key];return d?d.action==='approve'?(d.collection?'Build requested · draft':'Approved · choose collection'):d.action==='edit'?'Edit requested · draft':'Rejected · draft':p.delivery_status;}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.tab===tab)));const area=$('#content');area.replaceChildren();if(tab==='queue')area.append(el('p','These requests are device drafts until exported and imported by the agent. Saved owner choices appear separately from new device drafts.','notice'));if(tab==='library')area.append(el('p','Lot records and print access. Ready means recorded delivery evidence; revised heroes wait for matching delivery.','notice'));
const list=data.items.filter(p=>tab!=='queue'||(decisions[p.key]?.action==='approve'&&decisions[p.key]?.collection)||p.delivery_status==='Build / update queued');const grid=el('div',null,'grid');for(const p of list){const card=el('article',null,'card'),im=el('img');im.src=p.preview;im.alt=p.name+' full artwork';im.loading='lazy';card.append(im,el('h2',p.name),el('p',status(p),'meta'));card.append(el('p',p.saved_collection?`${p.saved_collection} · saved choice`:p.existing_collection||'Collection needed','meta'));
if(tab==='library'){card.append(el('p',`${p.photo_count} recorded lot images · ${p.recorded_stage}`,'meta'));const links=el('div',null,'links');if(p.board_url)links.append(link((p.owner_collection_pending||p.hero_edit_pending||p.delivery_status==='Build / update queued')?'Prior lot & copy ↗':'Lot & copy ↗',p.board_url));if(p.notion_url)links.append(link((p.owner_collection_pending||p.hero_edit_pending||p.delivery_status==='Build / update queued')?'Prior Notion · prints ↗':'Notion · print files ↗',p.notion_url));else links.append(el('span','Notion delivery pending'));card.append(links);}else{if(decisions[p.key]?.collection)card.append(el('p',decisions[p.key].collection));const b=el('button','Open artwork');b.onclick=()=>open(p);card.append(b);}grid.append(card);}if(!list.length)area.append(el('p','No build requests yet. Approve an artwork, then choose its collection.'));area.append(grid);}
function open(p){const detail=$('#detail');detail.replaceChildren();const image=el('img');image.src=p.preview;image.alt=p.name+' complete poster';const panel=el('div');panel.append(el('h2',p.name),el('p',status(p),'meta'));const full=link('Open full poster ↗',p.review_url||p.preview);panel.append(full);if(p.saved_collection)panel.append(el('p',`${p.saved_collection} · saved owner choice`,'meta'));const label=el('label','Requested changes');label.htmlFor='edit-note';const note=el('textarea');note.id='edit-note';note.maxLength=10000;note.placeholder='Tell the agent what to change…';note.value=decisions[p.key]?.note||'';panel.append(label,note);const actions=el('div',null,'actions');
for(const [action,title]of [['approve','Approve artwork'],['edit','Request edit'],['reject','Reject']]){const b=el('button',title);b.disabled=!p.source_sha256;b.onclick=()=>{if(action==='edit'&&!note.value.trim()){note.setCustomValidity('Describe the requested edit.');note.reportValidity();return;}note.setCustomValidity('');decisions[p.key]={key:p.key,source_sha256:p.source_sha256,action,note:note.value.trim(),collection:action==='approve'?(p.saved_collection||null):null,decided_at:new Date().toISOString()};persist();open(p);render();};actions.append(b);}panel.append(actions);
if(decisions[p.key]?.action==='approve'||(!decisions[p.key]&&p.recorded_approval==='approved')){const label=el('label','Choose the collection to request the build');label.htmlFor='collection';const select=el('select');select.id='collection';select.append(new Option('Choose collection…',''));for(const c of data.collections)select.append(new Option(c,c));select.value=decisions[p.key]?.collection||p.saved_collection||'';select.onchange=()=>{if(!decisions[p.key])decisions[p.key]={key:p.key,source_sha256:p.source_sha256,action:'approve',note:'',collection:null};decisions[p.key].collection=select.value||null;decisions[p.key].decided_at=new Date().toISOString();persist();render();};panel.append(label,select,el('p','Agent assembles prints, nine photos, copy and Notion delivery.','meta'));}
if(!p.source_sha256)panel.append(el('p','Source file unavailable. Decisions disabled until the exact master is bound.','notice'));const technical=el('details');technical.append(el('summary','Source binding'),el('code',p.source_sha256||'UNKNOWN'));panel.append(technical);detail.append(image,panel);if(!$('#review').open)$('#review').showModal();}
$('#close').onclick=()=>$('#review').close();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});
$('#copy').onclick=async()=>{const text=['Lombardia owner decisions — apply only to these exact source hashes.',...Object.values(decisions).map(d=>`${data.items.find(p=>p.key===d.key).name}\nLot: ${d.key}\nSHA256: ${d.source_sha256}\nDecision: ${d.action}\nCollection: ${d.collection||'not chosen — do not assign'}\nChanges: ${d.note||'none'}\nDecided: ${d.decided_at}`)].join('\n\n');try{await navigator.clipboard.writeText(text);$('#message').textContent='Copied. Paste and send in this task. Nothing has been sent automatically.';}catch{const box=el('textarea');box.value=text;box.setAttribute('aria-label','Decisions to copy and send');$('#message').replaceChildren(el('span','Copy this text and send in this task:'),box);box.focus();box.select();}};
$('#export').onclick=()=>{const payload={schema_version:1,kind:'lombardia_studio_decisions',exported_at:new Date().toISOString(),delivery_status:'export_only_not_applied',decisions:Object.values(decisions)};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download='lombardia-studio-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('#message').textContent='Decision file exported. Send it to the agent to apply. No remote save or build has occurred.';};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1024*1024)throw Error('File exceeds 1 MB.');const payload=JSON.parse(await file.text());if(payload.schema_version!==1||payload.kind!=='lombardia_studio_decisions'||!Array.isArray(payload.decisions))throw Error('Wrong decision format.');if(!payload.decisions.every(valid)||new Set(payload.decisions.map(d=>d.key)).size!==payload.decisions.length)throw Error('Unknown artwork, changed source, duplicate key or invalid decision. Nothing imported.');for(const d of payload.decisions)decisions[d.key]=d;persist();render();$('#message').textContent=`Imported ${payload.decisions.length} device drafts. No production state changed.`;}catch(error){$('#message').textContent=error.message;}finally{e.target.value='';}};
render();
